[project]
name = "repl-nix-web-site-using-flask"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.0.3",
    "flask-sqlalchemy>=3.1.1",
]